# Generated by Django 3.1.1 on 2020-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('GUITARS', (('ACOUSTIC', 'acoustic'), ('ELECTRIC', 'electric'))), ('AMPS', (('TUBE', 'tube'), ('SOLID STATE', 'solid state'))), ('CASES', (('SOFT CASES', 'soft cases'), ('HARD CASES', 'hard cases')))], default='GUITARS', max_length=30),
        ),
    ]
