# Generated by Django 3.1.1 on 2020-09-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('GUITARS', (('ACOUSTIC', 'acoustic'), ('ELECTRIC', 'electric'))), ('AMPS', (('TUBE AMP', 'tube'), ('SOLID STATE AMP', 'solid state'))), ('CASES', (('SOFT CASES', 'soft cases'), ('HARD CASES', 'hard cases')))], default='GUITARS', max_length=30),
        ),
    ]
