# Generated by Django 3.1.1 on 2020-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200909_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('GUITARS', (('ACOUSTIC GUITARS', 'acoustic'), ('ELECTRIC GUITARS', 'electric'))), ('AMPS', (('TUBE AMPS', 'tube'), ('SOLID STATE AMPS', 'solid state'))), ('CASES', (('SOFT CASES', 'soft cases'), ('HARD CASES', 'hard cases')))], default='GUITARS', max_length=30),
        ),
    ]
