# Generated by Django 3.1.1 on 2020-09-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200909_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products', to_field='product_name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('GUITARS', (('ACOUSTIC', 'acoustic'), ('ELECTRIC', 'electric'))), ('AMPS', (('TUBE AMPS', 'tube'), ('SOLID STATE AMPS', 'solid state'))), ('CASES', (('SOFT CASES', 'soft cases'), ('HARD CASES', 'hard cases')))], default='GUITARS', max_length=30),
        ),
    ]
