# Generated by Django 3.1.1 on 2020-09-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_email'),
        ('api', '0007_auto_20200911_1408'),
    ]

    operations = [
    ]
