# Generated by Django 3.1.1 on 2020-09-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200915_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product_name',
            new_name='product',
        ),
    ]
